name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: NixySoftware/.github/.github/workflows/commits.yml@473618d5365410901e83901c7d7066922a60ef4a # v0.3.1

    typescript:
        name: TypeScript
        uses: NixySoftware/.github/.github/workflows/typescript.yml@473618d5365410901e83901c7d7066922a60ef4a # v0.3.1
