name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: NixySoftware/.github/.github/workflows/commits.yml@6b03162f358358a3a6e814434ada3a73997714a9 # v0.6.0

    typescript:
        name: TypeScript
        uses: NixySoftware/.github/.github/workflows/typescript.yml@6b03162f358358a3a6e814434ada3a73997714a9 # v0.6.0
