name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: NixySoftware/.github/.github/workflows/commits.yml@d26fdb162526ba039af761c21650d24e52fd6ead # v0.5.2

    typescript:
        name: TypeScript
        uses: NixySoftware/.github/.github/workflows/typescript.yml@d26fdb162526ba039af761c21650d24e52fd6ead # v0.5.2
