name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        name: Publish
        uses: NixySoftware/.github/.github/workflows/publish.yml@d2eab9162b8786a1cccdc33b4725f3045e119927 # v0.5.1
        with:
            enable-rust: false
            enable-typescript: true
            typescript-registry-github: false
            typescript-registry-npm: true
