name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        name: Publish
        uses: NixySoftware/.github/.github/workflows/publish.yml@d26fdb162526ba039af761c21650d24e52fd6ead # v0.5.2
        with:
            enable-rust: false
            enable-typescript: true
            typescript-registry-github: false
            typescript-registry-npm: true
