name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

permissions:
    contents: read

jobs:
    pull-request:
        name: Pull Request
        uses: NixySoftware/.github/.github/workflows/pull-request.yml@473618d5365410901e83901c7d7066922a60ef4a # v0.3.1
