name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

permissions:
    contents: read

jobs:
    pull-request:
        name: Pull Request
        uses: NixySoftware/.github/.github/workflows/pull-request.yml@d26fdb162526ba039af761c21650d24e52fd6ead # v0.5.2
