name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: NixySoftware/.github/.github/workflows/release.yml@473618d5365410901e83901c7d7066922a60ef4a # v0.3.1
        with:
            bump: ${{ inputs.bump }}
            bump-rust: false
            bump-typescript: true
            bump-typescript-tool: 'npm'
            extract-version: 'typescript'
        secrets:
            app-client-id: ${{ secrets.APP_ID }}
            app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
