name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: NixySoftware/.github/.github/workflows/release.yml@d2eab9162b8786a1cccdc33b4725f3045e119927 # v0.5.1
        with:
            bump: ${{ inputs.bump }}
            bump-rust: false
            bump-typescript: true
            bump-typescript-tool: 'npm'
            extract-version: 'typescript'
        secrets:
            app-client-id: ${{ secrets.APP_ID }}
            app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
